/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 study_room.glb 
Author: scotty_n199 (https://sketchfab.com/scotty_n199)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/study-room-with-only-primitives-cgcookie-3d9a83ce7e3a49b39536a88ff9cad275
Title: Study Room with only Primitives - CGCookie
*/

import { useGLTF } from '@react-three/drei'

export function Study_room(props) {
  const { nodes, materials } = useGLTF('/models/study_room.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.502, 0.832, -1.35]} scale={[0.164, 0.295, 0.007]}>
            <mesh geometry={nodes.Object_120.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_122.geometry} material={materials.black_plastic} position={[0, -0.034, -0.914]} scale={[0.15, 0.889, 2]} />
            <mesh geometry={nodes.Object_124.geometry} material={materials.black_plastic} position={[0, 0.162, -1.829]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 5, 0.167]} />
          </group>
          <group position={[1.13, 0.832, -1.199]} scale={[0.164, 0.295, 0.007]}>
            <mesh geometry={nodes.Object_128.geometry} material={materials['Material.002']} />
            <mesh geometry={nodes.Object_130.geometry} material={materials.black_plastic} position={[0, -0.034, -0.914]} scale={[0.15, 0.889, 2]} />
            <mesh geometry={nodes.Object_132.geometry} material={materials.black_plastic} position={[0, 0.162, -1.829]} rotation={[Math.PI / 2, 0, 0]} scale={[0.3, 5, 0.167]} />
          </group>
          <mesh geometry={nodes.Object_4.geometry} material={materials.wood} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.wall} position={[-2, 1.25, 0]} rotation={[0, 0, Math.PI / 2]} scale={[0.09, 1, 0.107]} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.wall} position={[0, 1.25, -1.5]} rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[0.09, 1, 0.143]} />
          <mesh geometry={nodes.Object_10.geometry} material={materials['Material.001']} position={[-1.01, 0.615, -1.101]} scale={[0.826, 1, 1]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials['Material.001']} position={[-1.56, 0.49, -0.702]} rotation={[0, Math.PI / 2, 0]} scale={[0.7, 0.05, 0.3]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials['Material.001']} position={[-0.1, 0.281, -1.101]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['Material.001']} position={[-1.92, 0.281, -1.101]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials['Material.001']} position={[-1.56, 0.219, -0.042]} rotation={[0, Math.PI / 2, 0]} scale={[0.04, 0.222, 0.3]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.metal} position={[-0.954, 0.665, -1.212]} scale={[1, 0.714, 1]} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.black_plastic} position={[-0.954, 0.767, -1.413]} rotation={[0.929, 0, 0]} scale={[1, 0.286, 1]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.white_plastic} position={[-1.645, 0.762, -1.2]} scale={[1, 0.975, 1]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.material_0} position={[-1.655, 0.542, -0.211]} scale={[0.129, 0.002, 0.084]} />
          <mesh geometry={nodes.Object_28.geometry} material={materials.material_0} position={[-1.637, 0.546, -0.211]} rotation={[0, 0.18, 0]} scale={[0.129, 0.002, 0.084]} />
          <mesh geometry={nodes.Object_30.geometry} material={materials.material_0} position={[-1.661, 0.55, -0.204]} rotation={[0, -0.086, 0]} scale={[0.129, 0.002, 0.084]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.white_plastic} position={[-1.017, 0.667, -0.878]} scale={[0.808, 0.038, 0.313]} />
          <mesh geometry={nodes.Object_34.geometry} material={materials.material_0} position={[-0.215, 0.678, -1.435]} scale={[0.127, 0.013, 0.025]} />
          <mesh geometry={nodes.Object_36.geometry} material={materials['Material.002']} position={[-0.34, 0.781, -0.885]} rotation={[1.12, -0.234, 0.447]} scale={[0.162, 0.006, 0.103]} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.black_plastic} position={[-0.325, 0.671, -0.947]} rotation={[0, -0.501, 0]} scale={[0.171, 0.003, 0.11]} />
          <mesh geometry={nodes.Object_40.geometry} material={materials.black_plastic} position={[-1.697, 0.203, -1.098]} scale={[0.89, 0.207, 0.696]} />
          <mesh geometry={nodes.Object_42.geometry} material={materials.wood} position={[-1.459, 0.103, -0.609]} scale={[0.753, 1, 0.672]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.white_plastic} position={[-0.522, 0.716, -1.233]} rotation={[0, -0.622, 0]} scale={[0.083, 0.051, 0.051]} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.white_plastic} position={[-0.543, 0.798, -1.271]} rotation={[0, -0.642, 0]} scale={[0.025, 0.032, 0.025]} />
          <mesh geometry={nodes.Object_48.geometry} material={materials.black_plastic} position={[-0.533, 0.772, -1.212]} rotation={[0, 0.916, 0]} scale={[0.008, 0.005, 0.064]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.black_plastic} position={[-0.479, 0.785, -1.226]} scale={[0.042, 0.063, 0.042]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials.black_plastic} position={[-0.478, 0.836, -1.227]} scale={[0.008, 0.104, 0.008]} />
          <mesh geometry={nodes.Object_54.geometry} material={materials.metal} position={[-0.029, 0.703, -1.14]} scale={[0.013, 0.019, 0.349]} />
          <mesh geometry={nodes.Object_56.geometry} material={materials['Material.002']} position={[0.633, 0.716, -1.146]} scale={[0.65, 0.006, 0.343]} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.metal} position={[1.296, 0.703, -1.153]} scale={[0.013, 0.019, 0.349]} />
          <mesh geometry={nodes.Object_60.geometry} material={materials['Material.003']} position={[0.088, 0.862, -1.357]} scale={[0.208, 0.458, 0.208]} />
          <mesh geometry={nodes.Object_62.geometry} material={materials.metal} position={[0.633, 0.701, -0.812]} scale={[0.65, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_64.geometry} material={materials.metal} position={[0.633, 0.701, -1.146]} scale={[0.65, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_66.geometry} material={materials.metal} position={[0.633, 0.701, -1.49]} scale={[0.65, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials.metal} position={[1.296, 0.37, -0.908]} scale={[0.013, 0.315, 0.019]} />
          <mesh geometry={nodes.Object_70.geometry} material={materials.metal} position={[1.296, 0.37, -1.368]} scale={[0.013, 0.315, 0.019]} />
          <mesh geometry={nodes.Object_72.geometry} material={materials.metal} position={[-0.029, 0.37, -0.906]} scale={[0.013, 0.315, 0.019]} />
          <mesh geometry={nodes.Object_74.geometry} material={materials.metal} position={[-0.029, 0.37, -1.365]} scale={[0.013, 0.315, 0.019]} />
          <mesh geometry={nodes.Object_76.geometry} material={materials.metal} position={[0.633, 0.441, -1.353]} scale={[0.65, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_78.geometry} material={materials.metal} position={[0.633, 0.344, -1.353]} scale={[0.65, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_80.geometry} material={materials.metal} position={[-0.029, 0.036, -1.14]} scale={[0.013, 0.019, 0.349]} />
          <mesh geometry={nodes.Object_82.geometry} material={materials.metal} position={[1.296, 0.036, -1.153]} scale={[0.013, 0.019, 0.349]} />
          <mesh geometry={nodes.Object_84.geometry} material={materials.metal} position={[0.633, 0.062, -1.146]} scale={[0.65, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_86.geometry} material={materials.black_plastic} position={[0.877, 0.956, -1.338]} rotation={[0, -0.139, 0]} scale={[0.875, 0.542, 0.083]} />
          <mesh geometry={nodes.Object_88.geometry} material={materials.black_plastic} position={[0.878, 0.731, -1.34]} scale={[0.328, 0.02, 0.328]} />
          <mesh geometry={nodes.Object_90.geometry} material={materials.black_plastic} position={[0.242, 0.725, -1.063]} rotation={[0, -1.436, Math.PI]} scale={[0.171, 0.003, 0.11]} />
          <mesh geometry={nodes.Object_92.geometry} material={materials.black_plastic} position={[-0.593, 0.67, -0.887]} scale={[0.417, 0.004, 0.292]} />
          <mesh geometry={nodes.Object_94.geometry} material={materials.black_plastic} position={[-0.987, 0.672, -0.885]} scale={[0.831, 0.012, 0.3]} />
          <mesh geometry={nodes.Object_96.geometry} material={materials.metal} position={[0.382, 0.645, -0.978]} rotation={[0, Math.PI / 2, 0]} scale={[0.172, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_98.geometry} material={materials.metal} position={[0.856, 0.645, -0.978]} rotation={[0, Math.PI / 2, 0]} scale={[0.172, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_100.geometry} material={materials.metal} position={[0.375, 0.666, -0.978]} rotation={[0, Math.PI / 2, 0]} scale={[0.172, 0.027, 0.001]} />
          <mesh geometry={nodes.Object_102.geometry} material={materials.metal} position={[0.863, 0.666, -0.978]} rotation={[0, Math.PI / 2, 0]} scale={[0.172, 0.027, 0.001]} />
          <mesh geometry={nodes.Object_104.geometry} material={materials.black_plastic} position={[0.382, 0.645, -0.799]} rotation={[0, Math.PI / 2, 0]} scale={0.006} />
          <mesh geometry={nodes.Object_106.geometry} material={materials.black_plastic} position={[0.856, 0.645, -0.799]} rotation={[0, Math.PI / 2, 0]} scale={0.006} />
          <mesh geometry={nodes.Object_108.geometry} material={materials.metal} position={[0.619, 0.645, -0.799]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.23, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_110.geometry} material={materials.metal} position={[0.619, 0.645, -1.144]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.23, 0.006, 0.006]} />
          <mesh geometry={nodes.Object_112.geometry} material={materials['Material.002']} position={[0.619, 0.65, -0.966]} scale={[0.23, 0.002, 0.172]} />
          <mesh geometry={nodes.Object_114.geometry} material={materials.metal} position={[0.366, 0.693, -0.978]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.172, 0.007, 0.001]} />
          <mesh geometry={nodes.Object_116.geometry} material={materials.metal} position={[0.871, 0.693, -0.978]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.172, 0.007, 0.001]} />
          <mesh geometry={nodes.Object_118.geometry} material={materials.black_plastic} position={[0.502, 0.732, -1.398]} scale={[0.164, 0.033, 0.164]} />
          <mesh geometry={nodes.Object_126.geometry} material={materials.black_plastic} position={[1.13, 0.732, -1.247]} scale={[0.164, 0.033, 0.164]} />
          <mesh geometry={nodes.Object_134.geometry} material={materials.black_plastic} position={[0.861, 0.745, -1.318]} rotation={[0, 0.916, 0]} scale={[0.008, 0.005, 0.064]} />
          <mesh geometry={nodes.Object_136.geometry} material={materials.material_0} position={[-1.611, 0.878, -1.194]} rotation={[0, 0.426, 0]} scale={[0.295, 0.016, 0.344]} />
          <mesh geometry={nodes.Object_138.geometry} material={materials.material_0} position={[-1.657, 0.884, -1.296]} rotation={[0.995, 0.242, -0.354]} scale={[0.295, 0.016, 0.066]} />
          <mesh geometry={nodes.Object_140.geometry} material={materials.material_0} position={[-1.661, 0.918, -1.305]} rotation={[Math.PI / 2, 0, -0.426]} scale={[0.295, 0.016, 0.066]} />
          <mesh geometry={nodes.Object_142.geometry} material={materials.material_0} position={[-1.639, 0.978, -1.257]} rotation={[2.422, -0.329, -0.276]} scale={[0.295, 0.016, 0.23]} />
          <mesh geometry={nodes.Object_144.geometry} material={materials.white_plastic} position={[-1.46, 0.2, -0.286]} rotation={[0, Math.PI / 2, 0]} scale={[0.525, 0.591, 0.525]} />
          <mesh geometry={nodes.Object_146.geometry} material={materials.wood} position={[-1.46, 0.01, -0.286]} rotation={[0, Math.PI / 2, 0]} scale={[0.623, 0.033, 0.623]} />
          <mesh geometry={nodes.Object_148.geometry} material={materials.wood} position={[-1.66, 0.21, -0.286]} rotation={[0, Math.PI / 2, 0]} scale={[0.623, 0.036, 0.623]} />
          <mesh geometry={nodes.Object_150.geometry} material={materials.wood} position={[-1.46, 0.41, -0.286]} rotation={[0, Math.PI / 2, 0]} scale={[0.623, 0.033, 0.623]} />
          <mesh geometry={nodes.Object_152.geometry} material={materials.wood} position={[-1.46, 0.21, -0.106]} rotation={[0, Math.PI / 2, 0]} scale={[0.623, 0.033, 0.623]} />
          <mesh geometry={nodes.Object_154.geometry} material={materials.wood} position={[-1.46, 0.21, -0.466]} rotation={[0, Math.PI / 2, 0]} scale={[0.623, 0.033, 0.623]} />
          <mesh geometry={nodes.Object_156.geometry} material={materials.wood} position={[1.65, 0.406, -1.12]} scale={[0.722, 1.247, 0.607]} />
          <mesh geometry={nodes.Object_158.geometry} material={materials.wood} position={[1.65, 0.01, -1.12]} scale={[0.82, 0.033, 0.623]} />
          <mesh geometry={nodes.Object_160.geometry} material={materials.wood} position={[1.65, 0.945, -1.3]} scale={[0.732, 0.16, 0.623]} />
          <mesh geometry={nodes.Object_162.geometry} material={materials.wood} position={[1.413, 0.945, -1.12]} scale={[0.842, 0.16, 0.623]} />
          <mesh geometry={nodes.Object_164.geometry} material={materials.wood} position={[1.65, 1.48, -1.12]} scale={[0.722, 1.247, 0.607]} />
          <mesh geometry={nodes.Object_166.geometry} material={materials['Material.004']} position={[1.65, 0.865, -1.12]} scale={[0.722, 0.246, 0.607]} />
          <mesh geometry={nodes.Object_168.geometry} material={materials['Material.004']} position={[1.65, 1.019, -1.12]} scale={[0.722, 0.246, 0.607]} />
          <mesh geometry={nodes.Object_170.geometry} material={materials.wood} position={[1.65, 1.86, -1.12]} scale={[0.82, 0.033, 0.623]} />
          <mesh geometry={nodes.Object_172.geometry} material={materials.wood} position={[1.886, 0.945, -1.12]} scale={[0.842, 0.16, 0.623]} />
          <mesh geometry={nodes.Object_174.geometry} material={materials.metal} position={[1.704, 0.863, -0.925]} rotation={[Math.PI / 2, 0, 0]} scale={[0.213, 0.002, 0.033]} />
          <mesh geometry={nodes.Object_176.geometry} material={materials.metal} position={[1.613, 0.863, -0.925]} rotation={[Math.PI / 2, 0, 0]} scale={[0.213, 0.002, 0.033]} />
          <mesh geometry={nodes.Object_178.geometry} material={materials.metal} position={[1.658, 0.863, -0.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.213, 0.016, 0.033]} />
          <mesh geometry={nodes.Object_180.geometry} material={materials.metal} position={[1.704, 1.017, -0.925]} rotation={[Math.PI / 2, 0, 0]} scale={[0.213, 0.002, 0.033]} />
          <mesh geometry={nodes.Object_182.geometry} material={materials.metal} position={[1.613, 1.017, -0.925]} rotation={[Math.PI / 2, 0, 0]} scale={[0.213, 0.002, 0.033]} />
          <mesh geometry={nodes.Object_184.geometry} material={materials.metal} position={[1.658, 1.017, -0.91]} rotation={[Math.PI / 2, 0, 0]} scale={[0.213, 0.016, 0.033]} />
          <mesh geometry={nodes.Object_186.geometry} material={materials.metal} position={[1.481, 0.439, -0.925]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.213, 0.002, 0.033]} />
          <mesh geometry={nodes.Object_188.geometry} material={materials.metal} position={[1.481, 0.349, -0.925]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.213, 0.002, 0.033]} />
          <mesh geometry={nodes.Object_190.geometry} material={materials.metal} position={[1.481, 0.394, -0.91]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.213, 0.016, 0.033]} />
          <mesh geometry={nodes.Object_192.geometry} material={materials.metal} position={[1.481, 1.474, -0.925]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.213, 0.002, 0.033]} />
          <mesh geometry={nodes.Object_194.geometry} material={materials.metal} position={[1.481, 1.384, -0.925]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.213, 0.002, 0.033]} />
          <mesh geometry={nodes.Object_196.geometry} material={materials.metal} position={[1.481, 1.429, -0.91]} rotation={[Math.PI / 2, Math.PI / 2, 0]} scale={[0.213, 0.016, 0.033]} />
          <mesh geometry={nodes.Object_198.geometry} material={materials.black_plastic} position={[-0.954, 0.67, -1.339]} rotation={[0.922, 0, 0]} scale={[0.604, 0.714, 0.04]} />
          <mesh geometry={nodes.Object_200.geometry} material={materials.white_plastic} position={[-1.645, 0.868, -1.2]} scale={[1, 5, 1]} />
          <mesh geometry={nodes.Object_202.geometry} material={materials.white_plastic} position={[-1.645, 0.754, -0.999]} scale={[0.8, 0.9, 0.025]} />
          <mesh geometry={nodes.Object_204.geometry} material={materials.black_plastic} position={[-1.079, 0.671, -1.304]} scale={[0.025, 0.003, 0.016]} />
          <mesh geometry={nodes.Object_206.geometry} material={materials.material_0} position={[-1.079, 0.669, -1.304]} scale={[0.025, 0.003, 0.016]} />
          <mesh geometry={nodes.Object_208.geometry} material={materials.black_plastic} position={[-1.08, 0.671, -1.285]} scale={[0.025, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_210.geometry} material={materials.black_plastic} position={[-1.05, 0.671, -1.265]} scale={[0.025, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_212.geometry} material={materials.black_plastic} position={[-1.043, 0.671, -1.245]} scale={[0.025, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_214.geometry} material={materials.black_plastic} position={[-1.053, 0.671, -1.225]} scale={[0.025, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_216.geometry} material={materials.black_plastic} position={[-1.079, 0.671, -1.205]} scale={[0.025, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_218.geometry} material={materials.black_plastic} position={[-1.075, 0.671, -1.265]} scale={[0.043, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_220.geometry} material={materials.black_plastic} position={[-1.071, 0.671, -1.245]} scale={[0.054, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_222.geometry} material={materials.black_plastic} position={[-1.076, 0.671, -1.225]} scale={[0.039, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_224.geometry} material={materials.black_plastic} position={[-1.017, 0.671, -1.205]} scale={[0.038, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_226.geometry} material={materials.black_plastic} position={[-0.954, 0.671, -1.205]} scale={[0.153, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_228.geometry} material={materials.black_plastic} position={[-0.893, 0.671, -1.205]} scale={[0.038, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_230.geometry} material={materials.black_plastic} position={[-0.826, 0.671, -1.225]} scale={[0.066, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_232.geometry} material={materials.black_plastic} position={[-0.821, 0.671, -1.285]} scale={[0.043, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_234.geometry} material={materials.black_plastic} position={[-0.816, 0.671, -1.265]} scale={[0.026, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_236.geometry} material={materials.black_plastic} position={[-0.813, 0.671, -1.252]} scale={[0.016, 0.003, 0.049]} />
          <mesh geometry={nodes.Object_238.geometry} material={materials.black_plastic} position={[-0.83, 0.671, -1.21]} scale={[0.025, 0.003, 0.013]} />
          <mesh geometry={nodes.Object_240.geometry} material={materials.black_plastic} position={[-0.83, 0.671, -1.202]} scale={[0.025, 0.003, 0.013]} />
          <mesh geometry={nodes.Object_242.geometry} material={materials.black_plastic} position={[-0.846, 0.671, -1.202]} scale={[0.025, 0.003, 0.013]} />
          <mesh geometry={nodes.Object_244.geometry} material={materials.black_plastic} position={[-0.814, 0.671, -1.202]} scale={[0.025, 0.003, 0.013]} />
          <mesh geometry={nodes.Object_246.geometry} material={materials.black_plastic} position={[-0.659, 0.678, -0.899]} scale={[0.057, 0.024, 0.081]} />
          <mesh geometry={nodes.Object_248.geometry} material={materials.black_plastic} position={[-0.669, 0.679, -0.899]} scale={[0.027, 0.024, 0.081]} />
          <mesh geometry={nodes.Object_250.geometry} material={materials.black_plastic} position={[-0.65, 0.679, -0.899]} scale={[0.027, 0.024, 0.081]} />
          <mesh geometry={nodes.Object_252.geometry} material={materials.black_plastic} position={[-0.66, 0.679, -0.885]} scale={[0.057, 0.024, 0.037]} />
          <mesh geometry={nodes.Object_254.geometry} material={materials.black_plastic} position={[-0.659, 0.68, -0.905]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[0.034, 0.004, 0.034]} />
          <mesh geometry={nodes.Object_256.geometry} material={materials.black_plastic} position={[-0.379, 0.63, 0.01]} scale={[0.672, 0.672, 0.098]} />
          <mesh geometry={nodes.Object_258.geometry} material={materials.black_plastic} position={[-0.379, 0.395, -0.185]} rotation={[Math.PI / 2, 0, 0]} scale={[0.672, 0.738, 0.098]} />
          <mesh geometry={nodes.Object_260.geometry} material={materials.black_plastic} position={[-0.169, 0.478, 0.01]} scale={[0.016, 1.304, 0.013]} />
          <mesh geometry={nodes.Object_262.geometry} material={materials.black_plastic} position={[-0.152, 0.541, -0.08]} scale={[0.074, 0.246, 0.052]} />
          <mesh geometry={nodes.Object_264.geometry} material={materials.black_plastic} position={[-0.169, 0.402, -0.11]} scale={[0.016, 0.554, 0.066]} />
          <mesh geometry={nodes.Object_266.geometry} material={materials.black_plastic} position={[-0.152, 0.466, -0.231]} rotation={[-1.117, 0, 0]} scale={[0.074, 0.246, 0.039]} />
          <mesh geometry={nodes.Object_268.geometry} material={materials.black_plastic} position={[-0.606, 0.541, -0.08]} scale={[0.074, 0.246, 0.052]} />
          <mesh geometry={nodes.Object_270.geometry} material={materials.black_plastic} position={[-0.589, 0.402, -0.11]} scale={[0.016, 0.554, 0.066]} />
          <mesh geometry={nodes.Object_272.geometry} material={materials.black_plastic} position={[-0.589, 0.478, 0.01]} scale={[0.016, 1.304, 0.013]} />
          <mesh geometry={nodes.Object_274.geometry} material={materials.black_plastic} position={[-0.606, 0.466, -0.231]} rotation={[-1.117, 0, 0]} scale={[0.074, 0.246, 0.039]} />
          <mesh geometry={nodes.Object_276.geometry} material={materials.black_plastic} position={[-0.379, 0.215, -0.185]} scale={[0.082, 0.492, 0.082]} />
          <mesh geometry={nodes.Object_278.geometry} material={materials.black_plastic} position={[-0.379, 0.079, -0.051]} rotation={[0.162, 0, 0]} scale={[0.082, 0.041, 0.41]} />
          <mesh geometry={nodes.Object_280.geometry} material={materials.black_plastic} position={[-0.379, 0.096, -0.185]} scale={[0.131, 0.049, 0.131]} />
          <mesh geometry={nodes.Object_282.geometry} material={materials.black_plastic} position={[-0.251, 0.079, -0.144]} rotation={[0.487, 1.218, -0.461]} scale={[0.082, 0.041, 0.41]} />
          <mesh geometry={nodes.Object_284.geometry} material={materials.black_plastic} position={[-0.379, 0.03, 0.041]} rotation={[0, 0, -Math.PI / 2]} scale={0.098} />
          <mesh geometry={nodes.Object_286.geometry} material={materials.black_plastic} position={[-0.3, 0.079, -0.294]} rotation={[2.942, 0.619, -3.025]} scale={[0.082, 0.041, 0.41]} />
          <mesh geometry={nodes.Object_288.geometry} material={materials.black_plastic} position={[-0.458, 0.079, -0.294]} rotation={[2.942, -0.619, 3.025]} scale={[0.082, 0.041, 0.41]} />
          <mesh geometry={nodes.Object_290.geometry} material={materials.black_plastic} position={[-0.507, 0.079, -0.144]} rotation={[0.487, -1.218, 0.461]} scale={[0.082, 0.041, 0.41]} />
          <mesh geometry={nodes.Object_292.geometry} material={materials.black_plastic} position={[-0.165, 0.03, -0.112]} rotation={[0, 1.239, -Math.PI / 2]} scale={0.098} />
          <mesh geometry={nodes.Object_294.geometry} material={materials.black_plastic} position={[-0.243, 0.03, -0.365]} rotation={[-Math.PI, 0.646, Math.PI / 2]} scale={0.098} />
          <mesh geometry={nodes.Object_296.geometry} material={materials.black_plastic} position={[-0.509, 0.03, -0.37]} rotation={[Math.PI, -0.611, Math.PI / 2]} scale={0.098} />
          <mesh geometry={nodes.Object_298.geometry} material={materials.black_plastic} position={[-0.595, 0.03, -0.119]} rotation={[0, -1.274, -Math.PI / 2]} scale={0.098} />
          <mesh geometry={nodes.Object_300.geometry} material={materials.black_plastic} position={[0.881, 0.777, -1.363]} rotation={[0, -0.105, 0]} scale={[0.066, 0.131, 0.049]} />
          <mesh geometry={nodes.Object_302.geometry} material={materials.black_plastic} position={[-1.126, 0.768, -1.411]} rotation={[0.929, 0, 0]} scale={[0.055, 0.071, 1]} />
          <mesh geometry={nodes.Object_304.geometry} material={materials.black_plastic} position={[-0.782, 0.768, -1.411]} rotation={[0.929, 0, 0]} scale={[0.055, 0.071, 1]} />
          <mesh geometry={nodes.Object_306.geometry} material={materials.black_plastic} position={[-0.782, 0.768, -1.411]} rotation={[0.929, 0, 0]} scale={[0.055, 0.071, 1]} />
          <mesh geometry={nodes.Object_308.geometry} material={materials.black_plastic} position={[-0.954, 0.86, -1.48]} rotation={[0.929, 0, 0]} scale={[0.89, 0.071, 0.08]} />
          <mesh geometry={nodes.Object_310.geometry} material={materials.black_plastic} position={[-0.954, 0.676, -1.342]} rotation={[0.929, 0, 0]} scale={[0.89, 0.071, 0.08]} />
          <mesh geometry={nodes.Object_312.geometry} material={materials.black_plastic} position={[-1.898, 1.2, -1.068]} rotation={[1.451, 0.054, -0.423]} scale={[0.01, 0.001, 0.168]} />
          <mesh geometry={nodes.Object_314.geometry} material={materials.black_plastic} position={[-1.618, 1.158, -1.212]} rotation={[1.451, 0.054, -0.423]} scale={[0.325, 0.02, 0.208]} />
          <mesh geometry={nodes.Object_316.geometry} material={materials.black_plastic} position={[-1.324, 1.2, -1.328]} rotation={[1.451, 0.054, -0.423]} scale={[0.01, 0.001, 0.168]} />
          <mesh geometry={nodes.Object_318.geometry} material={materials.metal} position={[-1.6, 0.994, -1.173]} rotation={[1.451, 0.054, -0.423]} scale={[0.325, 0.001, 0.04]} />
          <mesh geometry={nodes.Object_320.geometry} material={materials.black_plastic} position={[-1.603, 1.044, -1.179]} rotation={[1.451, 0.054, -0.423]} scale={[0.305, 0.001, 0.01]} />
          <mesh geometry={nodes.Object_322.geometry} material={materials.black_plastic} position={[-1.62, 1.357, -1.217]} rotation={[1.451, 0.054, -0.423]} scale={[0.305, 0.001, 0.01]} />
          <mesh geometry={nodes.Object_324.geometry} material={materials.black_plastic} position={[-0.328, 0.883, -0.937]} rotation={[1.12, -0.234, 0.447]} scale={[0.187, 0.001, 0.01]} />
          <mesh geometry={nodes.Object_326.geometry} material={materials.black_plastic} position={[-0.381, 0.684, -0.84]} rotation={[1.12, -0.234, 0.447]} scale={[0.187, 0.001, 0.01]} />
          <mesh geometry={nodes.Object_328.geometry} material={materials.black_plastic} position={[-0.499, 0.781, -0.973]} rotation={[1.12, -0.234, 0.447]} scale={[0.02, 0.006, 0.103]} />
          <mesh geometry={nodes.Object_330.geometry} material={materials.black_plastic} position={[-0.193, 0.781, -0.805]} rotation={[1.12, -0.234, 0.447]} scale={[0.005, 0.006, 0.103]} />
          <mesh geometry={nodes.Object_332.geometry} material={materials.black_plastic} position={[-0.352, 0.78, -0.894]} rotation={[1.12, -0.234, 0.447]} scale={[0.187, 0.006, 0.124]} />
          <mesh geometry={nodes.Object_334.geometry} material={materials.black_plastic} position={[-0.87, 0.671, -1.205]} scale={[0.025, 0.003, 0.025]} />
          <mesh geometry={nodes.Object_336.geometry} material={materials.black_plastic} position={[-0.495, 0.819, -0.986]} rotation={[1.12, -0.234, 0.447]} scale={[1, 0.5, 0.667]} />
          <mesh geometry={nodes.Object_338.geometry} material={materials.black_plastic} position={[-0.498, 0.805, -0.979]} rotation={[1.12, -0.234, 0.447]} scale={[1, 0.5, 0.667]} />
          <mesh geometry={nodes.Object_340.geometry} material={materials.black_plastic} position={[-0.508, 0.77, -0.962]} rotation={[1.12, -0.234, 0.447]} scale={[1, 0.5, 0.667]} />
          <mesh geometry={nodes.Object_342.geometry} material={materials.black_plastic} position={[-0.511, 0.756, -0.955]} rotation={[1.12, -0.234, 0.447]} scale={[1, 0.5, 0.667]} />
          <mesh geometry={nodes.Object_344.geometry} material={materials.black_plastic} position={[-0.503, 0.788, -0.971]} rotation={[0.905, 0.22, 0.446]} scale={[0.032, 0.002, 0.032]} />
          <mesh geometry={nodes.Object_346.geometry} material={materials.black_plastic} position={[-0.503, 0.788, -0.97]} rotation={[0.905, 0.22, 0.446]} scale={[0.008, 0, 0.008]} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/study_room.glb')
